const state={news:[],source:'all',query:'',date:'',view:'news'};
const store={get:(k,d)=>JSON.parse(localStorage.getItem('dne_'+k)||JSON.stringify(d)),set:(k,v)=>localStorage.setItem('dne_'+k,JSON.stringify(v))};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let vocab=store.get('vocab',{}),notes=store.get('notes',{}),lookupLog=store.get('lookupLog',[]);
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1600)}
async function loadNews(date=''){try{const path=date?`data/archive/${date}.json`:'data/news.json';const r=await fetch(path+'?v='+Date.now());if(!r.ok)throw Error();const d=await r.json();state.news=d.items||[];$('#updatedDate').textContent=d.date||'—';$('#sourceStatus').textContent=`${state.news.length} 条 · ${d.sources?.length||0} 个媒体来源`;buildSources();renderNews()}catch{$('#sourceStatus').textContent='暂时没有该日期的归档';state.news=[];renderNews()}}
function buildSources(){const sources=[...new Set(state.news.map(x=>x.source))];$('#sourceFilters').innerHTML='<button class="chip active" data-source="all">全部</button>'+sources.map(s=>`<button class="chip" data-source="${esc(s)}">${esc(s)}</button>`).join('');$$('#sourceFilters button').forEach(b=>b.onclick=()=>{$$('#sourceFilters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.source=b.dataset.source;renderNews()})}
function renderNews(){const q=state.query.toLowerCase();const list=state.news.filter(x=>(state.source==='all'||x.source===state.source)&&(!q||`${x.title} ${x.summary} ${x.source}`.toLowerCase().includes(q)));$('#resultCount').textContent=`${list.length} 条新闻`;$('#newsList').innerHTML=list.length?list.map(x=>`<article class="news-card" data-id="${x.id}"><div><div class="meta"><span class="source-badge">${esc(x.source)}</span><span>${formatTime(x.published)}</span>${x.mediaType?`<span class="media-badge">${x.mediaType==='audio'?'音频':'视频'}</span>`:''}${x.transcript?'<span class="media-badge">文稿</span>':''}</div><h3>${esc(x.title)}</h3><p>${esc(x.summary)}</p></div><span class="card-arrow">→</span></article>`).join(''):'<div class="empty-state">没有找到符合条件的新闻。</div>';$$('.news-card').forEach(c=>c.onclick=()=>openArticle(c.dataset.id));stats()}
function formatTime(s){if(!s)return'';try{return new Intl.DateTimeFormat('zh-CN',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(s))}catch{return s}}
function clickable(text){return esc(text).replace(/\b([A-Za-z][A-Za-z'’-]{1,})\b/g,'<span class="word" data-word="$1">$1</span>')}
function openArticle(id){const x=state.news.find(n=>n.id===id);if(!x)return;const media=x.mediaUrl?`<div class="media-box">${x.mediaType==='audio'?`<audio controls src="${esc(x.mediaUrl)}"></audio>`:`<video controls playsinline src="${esc(x.mediaUrl)}"></video>`}</div>`:'';$('#articleContent').innerHTML=`<article class="article"><div class="meta"><span class="source-badge">${esc(x.source)}</span><span>${formatTime(x.published)}</span></div><h1>${esc(x.title)}</h1>${media}<div class="article-summary">${clickable(x.summary||'该RSS仅提供标题，请前往官方页面阅读。')}</div><div class="article-actions"><a href="${esc(x.link)}" target="_blank" rel="noopener">阅读官方全文</a>${x.transcriptUrl?`<a class="secondary" href="${esc(x.transcriptUrl)}" target="_blank" rel="noopener">查看官方文稿</a>`:''}</div><div class="annotation"><label>我的新闻批注</label><textarea rows="4" data-note="${x.id}" placeholder="记录观点、句型或学习心得…">${esc(notes[x.id]||'')}</textarea></div></article>`;$$('.word').forEach(w=>w.onclick=e=>{e.stopPropagation();lookup(w.dataset.word)});const ta=$('[data-note]');ta.oninput=()=>{notes[x.id]=ta.value;store.set('notes',notes);stats()};$('#articleDialog').showModal()}
async function lookup(raw){const word=raw.toLowerCase().replace(/[^a-z'-]/g,'');if(!word)return;$('#lookupInput').value=word;$('#dictionaryResult').innerHTML='正在查询…';lookupLog.push({word,time:Date.now()});store.set('lookupLog',lookupLog);try{const r=await fetch(`https://api.dictionaryapi.dev/api/v2/entries/en/${encodeURIComponent(word)}`);if(!r.ok)throw Error();const d=(await r.json())[0];const meanings=(d.meanings||[]).slice(0,3).map(m=>`<div class="meaning"><b>${esc(m.partOfSpeech)}</b><br>${(m.definitions||[]).slice(0,2).map((v,i)=>`${i+1}. ${esc(v.definition)}${v.example?`<br><small>例：${esc(v.example)}</small>`:''}`).join('<br>')}</div>`).join('');$('#dictionaryResult').innerHTML=`<div><b class="dict-word">${esc(d.word)}</b><span class="phonetic">${esc(d.phonetic||'')}</span>${meanings}<button class="save-word" data-save="${esc(word)}">＋ 加入生词本</button></div>`;$('[data-save]').onclick=()=>saveWord(word,d)}catch{$('#dictionaryResult').innerHTML=`<b class="dict-word">${esc(word)}</b><div class="meaning">暂未查到释义。可以检查拼写，或前往词典继续查询。</div><a href="https://www.merriam-webster.com/dictionary/${encodeURIComponent(word)}" target="_blank">打开 Merriam-Webster</a>`}stats()}
function saveWord(word,d){const defs=(d.meanings||[]).flatMap(m=>(m.definitions||[]).slice(0,1).map(x=>`${m.partOfSpeech}: ${x.definition}`));const old=vocab[word]||{};vocab[word]={word,phonetic:d.phonetic||'',definitions:defs.slice(0,3),note:old.note||'',count:(old.count||0)+1,created:old.created||Date.now()};store.set('vocab',vocab);toast('已加入生词本');stats()}
function renderVocab(){let list=Object.values(vocab),q=$('#vocabSearch').value.toLowerCase(),sort=$('#vocabSort').value;list=list.filter(x=>`${x.word} ${x.definitions.join(' ')} ${x.note}`.toLowerCase().includes(q));if(sort==='az')list.sort((a,b)=>a.word.localeCompare(b.word));else if(sort==='freq')list.sort((a,b)=>b.count-a.count);else list.sort((a,b)=>b.created-a.created);$('#vocabList').innerHTML=list.length?list.map(v=>`<article class="vocab-card" data-vocab="${esc(v.word)}"><div class="vocab-top"><div><h3>${esc(v.word)}</h3><small>${esc(v.phonetic)}</small></div><button data-delete="${esc(v.word)}">删除</button></div><p>${v.definitions.map(esc).join('<br>')}</p><textarea rows="3" data-vnote="${esc(v.word)}" placeholder="写下中文意思、记忆方法或自己的例句…">${esc(v.note)}</textarea><div class="vocab-foot"><span>查询/收藏 ${v.count} 次</span><span>${new Date(v.created).toLocaleDateString('zh-CN')}</span></div></article>`).join(''):'<div class="empty-state">生词本还是空的。阅读新闻时点按单词，把它们收进来吧。</div>';$$('[data-vnote]').forEach(t=>t.oninput=()=>{vocab[t.dataset.vnote].note=t.value;store.set('vocab',vocab)});$$('[data-delete]').forEach(b=>b.onclick=()=>{delete vocab[b.dataset.delete];store.set('vocab',vocab);renderVocab();stats()})}
function switchView(v){state.view=v;$('#newsView').hidden=v!=='news';$('#vocabView').hidden=v!=='vocab';$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===v));if(v==='vocab')renderVocab()}
function stats(){const today=new Date().toDateString();$('#vocabCount').textContent=Object.keys(vocab).length;$('#lookupsToday').textContent=lookupLog.filter(x=>new Date(x.time).toDateString()===today).length;$('#notesCount').textContent=Object.values(notes).filter(Boolean).length}
$$('.nav-btn').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$('#searchInput').oninput=e=>{state.query=e.target.value;renderNews()};$('#datePicker').onchange=e=>loadNews(e.target.value);$('#lookupForm').onsubmit=e=>{e.preventDefault();lookup($('#lookupInput').value)};$('#vocabSearch').oninput=renderVocab;$('#vocabSort').onchange=renderVocab;$('#articleDialog .dialog-close').onclick=()=>$('#articleDialog').close();$('#exportVocab').onclick=()=>{const rows=['word\tphonetic\tdefinition\tnote',...Object.values(vocab).map(v=>[v.word,v.phonetic,v.definitions.join('; '),v.note].join('\t'))];const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([rows.join('\n')],{type:'text/tab-separated-values'}));a.download='我的英语生词本.tsv';a.click()};stats();loadNews();
